spring:
  application:
    name: SystemTester
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/systemtesterservice
logging:
  level:
    org:
      springframework:
        ampq:
          rabbit:
            core:
              RabbitAdmin: DEBUG
management:
  endpoint:
    configprops:
      enabled: true

server:
  port: 8089
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param

# Subscribe this tester on all exchanges to calculate the metrics
amqp:
  exchange:
    wavestream: wave-stream-change
    analytics: analytics-report
  queue:
    systemtester: system-tester-queue
  routingkey: 
    wavestream: wave-stream-key
    analytics: analytics-report-key
  
